"""
alert_store.py
───────────────
Stores alerts generated by Cognee search results.
Alerts are created by asking Cognee to find risks — NOT keyword scanning.
"""

import json
import uuid
from datetime import datetime
from pathlib import Path

ALERTS_PATH = Path(__file__).parent / "alerts.json"


def _read() -> list[dict]:
    if not ALERTS_PATH.exists():
        ALERTS_PATH.write_text("[]")
    return json.loads(ALERTS_PATH.read_text())


def _write(data: list) -> None:
    ALERTS_PATH.write_text(json.dumps(data, indent=2))


def create_alert(
    patient_id:   str,
    patient_name: str,
    title:        str,
    description:  str,
    alert_type:   str = "warning",   # "critical" | "warning" | "info"
    source:       str = "upload",    # "upload" | "chat" | "brief"
) -> dict:
    alert = {
        "id":           str(uuid.uuid4()),
        "patient_id":   patient_id,
        "patient_name": patient_name,
        "type":         alert_type,
        "title":        title,
        "desc":         description,
        "source":       source,
        "read":         False,
        "created_at":   datetime.now().isoformat(),
    }
    alerts = _read()
    alerts.insert(0, alert)  # newest first
    _write(alerts)
    return alert


def get_all_alerts() -> list[dict]:
    return _read()


def get_unread_count() -> int:
    return sum(1 for a in _read() if not a["read"])


def mark_read(alert_id: str) -> bool:
    alerts = _read()
    for a in alerts:
        if a["id"] == alert_id:
            a["read"] = True
            _write(alerts)
            return True
    return False


def dismiss(alert_id: str) -> bool:
    alerts = _read()
    new = [a for a in alerts if a["id"] != alert_id]
    if len(new) < len(alerts):
        _write(new)
        return True
    return False


def mark_all_read() -> None:
    alerts = _read()
    for a in alerts:
        a["read"] = True
    _write(alerts)
