"""
routes/alerts.py
─────────────────
Alert management endpoints.
Alerts are generated by Cognee graph search — not keyword scanning.
"""

from fastapi import APIRouter, HTTPException
from alert_store import (
    get_all_alerts, get_unread_count,
    mark_read, dismiss, mark_all_read,
)

router = APIRouter(prefix="/alerts", tags=["alerts"])


@router.get("")
async def list_alerts():
    """Return all alerts — used by Alerts page."""
    return {
        "alerts":       get_all_alerts(),
        "unread_count": get_unread_count(),
    }


@router.get("/count")
async def unread_count():
    """Sidebar badge count — polled every 30s by frontend."""
    return {"unread": get_unread_count()}


@router.patch("/{alert_id}/read")
async def mark_alert_read(alert_id: str):
    if not mark_read(alert_id):
        raise HTTPException(status_code=404, detail="Alert not found")
    return {"message": "Marked as read", "unread": get_unread_count()}


@router.delete("/{alert_id}")
async def dismiss_alert(alert_id: str):
    if not dismiss(alert_id):
        raise HTTPException(status_code=404, detail="Alert not found")
    return {"message": "Alert dismissed", "unread": get_unread_count()}


@router.post("/mark-all-read")
async def mark_all():
    mark_all_read()
    return {"message": "All alerts marked as read", "unread": 0}
