"use client";
import { useState, useEffect } from "react";
import Sidebar from "@/components/Sidebar";
import { IconAlertTriangle, IconShield, IconActivity, IconCheck, IconX, IconBell, IconEye } from "@/components/Icons";
import { api } from "@/lib/api";
import { alertBullets, alertHeadline } from "@/lib/formatAlert";

const TYPE_ICON: Record<string, any> = {
  critical: IconShield,
  warning:  IconAlertTriangle,
  info:     IconActivity,
};

const FILTERS = ["All","Critical","Warning","Info","Unread","Read"] as const;
type Filter = typeof FILTERS[number];

export default function AlertsPage() {
  const [alerts,  setAlerts]  = useState<any[]>([]);
  const [loading, setLoading] = useState(true);
  const [filter,  setFilter]  = useState<Filter>("All");

  const load = async () => {
    try {
      const data = await api.getAlerts();
      setAlerts(data.alerts || []);
    } catch {}
    setLoading(false);
  };

  useEffect(() => { load(); }, []);

  const markRead = async (id: string) => {
    await api.markRead(id);
    setAlerts(a => a.map(x => x.id===id ? {...x,read:true} : x));
  };

  const dismiss = async (id: string) => {
    await api.dismissAlert(id);
    setAlerts(a => a.filter(x => x.id!==id));
  };

  const markAll = async () => {
    await api.markAllRead();
    setAlerts(a => a.map(x => ({...x,read:true})));
  };

  const filtered = alerts.filter(a => {
    if (filter==="All")      return true;
    if (filter==="Unread")   return !a.read;
    if (filter==="Read")     return a.read;
    return a.type===filter.toLowerCase();
  });

  const unread = alerts.filter(a => !a.read).length;

  const COLOR: Record<string, {color:string;bg:string}> = {
    critical: { color:"#e05a3a", bg:"#280e06" },
    warning:  { color:"#f0a030", bg:"#1e1200" },
    info:     { color:"#4090e0", bg:"#041525" },
  };

  return (
    <div className="app-shell">
      <Sidebar />
      <main className="main-area">
        <div className="page-header">
          <div>
            <div className="text-[17px] font-bold text-white flex items-center gap-2">
              Alerts
              {unread > 0 && (
                <span className="text-[10px] font-bold bg-rose text-white px-2 py-0.5 rounded-full">
                  {unread} new
                </span>
              )}
            </div>
            <div className="text-[11px] text-ink-muted mt-0.5">
              {alerts.length} total · {unread} unread · Generated by Cognee graph search
            </div>
          </div>
          <button className="btn-secondary text-[11px]" onClick={markAll}>
            <IconCheck size={13} /> Mark all read
          </button>
        </div>

        <div className="page-content">
          {/* Summary */}
          <div className="grid grid-cols-3 gap-3 mb-5">
            {[
              { label:"Critical", type:"critical", color:"#e05a3a", bg:"linear-gradient(135deg,#280e06,#350f05)" },
              { label:"Warning",  type:"warning",  color:"#f0a030", bg:"linear-gradient(135deg,#1e1200,#2a1d00)" },
              { label:"Info",     type:"info",     color:"#4090e0", bg:"linear-gradient(135deg,#041525,#071e38)" },
            ].map(s => (
              <div key={s.label} className="rounded-2xl p-4 text-center border animate-fade-up"
                style={{ background:s.bg, borderColor:`${s.color}40` }}>
                <div className="text-[26px] font-bold" style={{ color:s.color }}>
                  {alerts.filter(a=>a.type===s.type).length}
                </div>
                <div className="text-[10px] text-ink-muted uppercase tracking-widest mt-1">{s.label}</div>
              </div>
            ))}
          </div>

          {/* Filters */}
          <div className="flex gap-2 mb-5 flex-wrap">
            {FILTERS.map(f => (
              <button key={f} onClick={() => setFilter(f)}
                className={`text-[11px] font-semibold px-4 py-1.5 rounded-full border transition-all cursor-pointer ${
                  filter===f ? "bg-teal text-bg-base border-teal" : "bg-bg-card border-line text-ink-muted hover:border-teal/30 hover:text-teal"
                }`}>
                {f}
              </button>
            ))}
          </div>

          {loading ? (
            <div className="flex items-center justify-center py-20">
              <div className="w-8 h-8 rounded-full border-2 border-teal/20 border-t-teal animate-spin-slow" />
            </div>
          ) : filtered.length === 0 ? (
            <div className="text-center py-20 animate-fade-in">
              <div className="w-14 h-14 bg-bg-card border border-line rounded-2xl flex items-center justify-center mx-auto mb-3">
                <IconCheck size={24} className="text-teal" />
              </div>
              <div className="text-[14px] font-semibold text-white mb-1">All clear</div>
              <div className="text-[12px] text-ink-muted">
                {alerts.length===0 ? "No alerts yet — upload patient documents to detect risks" : "No alerts matching this filter"}
              </div>
            </div>
          ) : (
            <div>
              {filtered.map((alert, i) => {
                const c  = COLOR[alert.type] || COLOR.info;
                const IC = TYPE_ICON[alert.type] || IconBell;
                return (
                  <div key={alert.id}
                    className="flex items-start gap-3 p-4 rounded-xl border mb-3 hover:border-line-strong transition-all animate-fade-up"
                    style={{ background:alert.read?"transparent":c.bg, borderColor:alert.read?"#1a2436":`${c.color}40`, animationDelay:`${i*0.05}s` }}>
                    <div className="w-9 h-9 rounded-xl flex items-center justify-center flex-shrink-0 mt-0.5"
                      style={{ background:alert.read?"#0f1520":`${c.color}20`, border:`0.5px solid ${c.color}40` }}>
                      <IC size={16} color={alert.read?"#4a6080":c.color} />
                    </div>
                    <div className="flex-1 min-w-0">
                      <div className="flex items-start justify-between gap-3 mb-1">
                        <div className={`text-[13px] font-semibold ${alert.read?"text-ink-soft":"text-white"}`}>
                          {alert.title}
                        </div>
                        <div className="flex items-center gap-1.5 flex-shrink-0">
                          {!alert.read && <span className="w-2 h-2 rounded-full" style={{ background:c.color }} />}
                          <span className="text-[10px] font-semibold px-2 py-0.5 rounded-full border"
                            style={{ color:c.color, background:c.bg, borderColor:`${c.color}40` }}>
                            {alert.type}
                          </span>
                        </div>
                      </div>
                      <p className="text-[11px] text-ink-muted leading-relaxed mb-2">
                        {(() => {
                          const bullets = alertBullets(alert.desc || alert.description || "");
                          if (bullets.length > 1) {
                            return (
                              <ul className="list-disc pl-4 space-y-1">
                                {bullets.map((item, i) => (
                                  <li key={i}>{item}</li>
                                ))}
                              </ul>
                            );
                          }
                          return alertHeadline(alert.desc || alert.description || "", alert.title);
                        })()}
                      </p>
                      <div className="flex items-center gap-3 text-[10px] text-ink-muted">
                        <span className="flex items-center gap-1">
                          <span className="w-1.5 h-1.5 rounded-full" style={{ background:c.color }} />
                          {alert.patient_name}
                        </span>
                        <span>{alert.source}</span>
                        <span>{new Date(alert.created_at).toLocaleDateString()}</span>
                      </div>
                    </div>
                    <div className="flex flex-col gap-1.5 flex-shrink-0">
                      {!alert.read && (
                        <button onClick={() => markRead(alert.id)}
                          className="btn-ghost text-[10px] px-2 py-1.5 rounded-lg hover:text-teal flex items-center gap-1">
                          <IconEye size={12} /> Read
                        </button>
                      )}
                      <button onClick={() => dismiss(alert.id)}
                        className="btn-ghost text-[10px] px-2 py-1.5 rounded-lg hover:text-rose flex items-center gap-1">
                        <IconX size={12} /> Dismiss
                      </button>
                    </div>
                  </div>
                );
              })}
            </div>
          )}
        </div>
      </main>
    </div>
  );
}
